name: Run PHP Script Every 30s

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: curl, json
        
    - name: Run script every 30 seconds
      run: |
        echo "🚀 Starting script loop..."
        start_time=$(date +%s)
        max_runtime=3300  # 55 minutes
        
        while true; do
          current_time=$(date +%s)
          elapsed=$((current_time - start_time))
          
          if [ $elapsed -gt $max_runtime ]; then
            echo "⏰ Time limit reached, stopping..."
            break
          fi
          
          echo "📅 $(date) - Running script.php..."
          php script.php
          
          echo "✅ Script completed. Waiting 30 seconds..."
          sleep 30
        done
        
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: script-results-${{ github.run_number }}
        path: |
          *.json
          *.log
        retention-days: 3
