name: Run PHP Script

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  run-php-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Change if you need another version

      - name: Run PHP script
        run: php script-v2.php
